name: galaxy_mini
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  uuid: ^4.4.2
  flutter_speed_dial: ^7.0.0
  reorderable_grid_view: ^2.2.8
  flutter_reorderable_list: ^1.3.1
  audioplayers: ^6.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/

flutter_launcher_icons:
  image_path: "assets/logo1.PNG"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo1.PNG"
  background_color_ios: "#FFFFFF"
