name: galaxy_mini
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  uuid: ^4.4.2
  flutter_speed_dial: ^7.0.0
  reorderable_grid_view: ^2.2.8
  flutter_reorderable_list: ^1.3.1
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.0
  flutter_blue: ^0.8.0
  permission_handler: ^11.3.1
  blue_thermal_printer: ^1.2.3
  get:
  flutter_reactive_ble: ^5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/icons/
     - assets/logos/
     - assets/audio/

flutter_launcher_icons:
  image_path: "assets/logos/logo2.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_padding: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/logo2.png"
